import pandas as pd
import os
import datetime
from .plotter import Plotter

class ReportGenerator:
    """Generates a comprehensive Markdown report."""
    
    def __init__(self, output_dir: str = "results"):
        self.output_dir = output_dir
        self.plotter = Plotter(output_dir)

    def generate_report(self, results_df: pd.DataFrame, complexity_df: pd.DataFrame = None, filename: str = "PERFORMANCE_REPORT.md"):
        """Creates the report with tables and embedded image links."""
        
        # Generate Charts
        # Use job-specific prefixes for charts if possible, but for now we'll just keep it simple 
        # or update the plotter to accept filenames
        time_chart = self.plotter.plot_time_vs_size(results_df)
        mem_chart = self.plotter.plot_memory_vs_size(results_df)
        bar_chart = self.plotter.plot_algorithm_comparison(results_df)
        
        report_path = os.path.join(self.output_dir, filename)
        
        with open(report_path, "w") as f:
            f.write(f"# Algorithm Performance Report\n")
            f.write(f"**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            
            f.write("## 1. Summary Statistics\n")
            f.write(results_df.to_markdown(index=False))
            f.write("\n\n")
            
            if complexity_df is not None:
                f.write("## 2. Complexity Validation\n")
                f.write(complexity_df.to_markdown(index=False))
                f.write("\n\n")
            
            f.write("## 3. Visualizations\n")
            
            f.write("### Time Complexity Analysis\n")
            f.write(f"![Time vs Size](time_complexity.png)\n\n")
            
            f.write("### Memory Usage Analysis\n")
            f.write(f"![Memory vs Size](memory_usage.png)\n\n")
            
            f.write("### Comparative Performance (Max Input)\n")
            f.write(f"![Comparison](comparison_bar.png)\n\n")
            
            f.write("## 4. Observations\n")
            best_algo = results_df.loc[results_df['Mean Time (s)'].idxmin()]
            f.write(f"- The fastest algorithm overall was **{best_algo['Algorithm']}**.\n")
            
            # Identify high memory usage
            max_mem = results_df.loc[results_df['Peak Memory (B)'].idxmax()]
            f.write(f"- The algorithm with highest peak memory was **{max_mem['Algorithm']}** ({max_mem['Peak Memory (B)']} bytes).\n")
            
            f.write("\n---\n*Generated by Algorithm Performance Analyzer*")
            
        return report_path
